@echo off
chcp 65001 >nul
title Windows Server 2022 一键极限精简优化 (Azure专用)

:: ============================================================
:: 自动请求管理员权限
:: ============================================================
net session >nul 2>&1
if %errorlevel% neq 0 (
    echo 正在请求管理员权限，请在弹出窗口中点击"是"...
    powershell -Command "Start-Process '%~f0' -Verb RunAs"
    exit /b
)

echo.
echo ============================================================
echo   Windows Server 2022 一键极限精简优化脚本
echo   Azure 2核1G 低配虚拟机专用  ^| 含Defender关闭
echo ============================================================
echo.

:: 将内嵌PowerShell脚本写入临时文件再执行，避免转义问题
set "PS1=%TEMP%\azure_optimize.ps1"

type nul > "%PS1%"
echo $ErrorActionPreference = 'SilentlyContinue'>> "%PS1%"
echo $ProgressPreference    = 'SilentlyContinue'>> "%PS1%"
echo.>> "%PS1%"
echo # ── 1. 语言 / 时区 ─────────────────────────────────────────>> "%PS1%"
echo Write-Host ''>> "%PS1%"
echo Write-Host '【1/10】切换系统语言为简体中文 + 时区 UTC+8...' -ForegroundColor Cyan>> "%PS1%"
echo Set-WinSystemLocale zh-CN>> "%PS1%"
echo Set-WinUILanguageOverride -Language zh-CN>> "%PS1%"
echo Set-Culture zh-CN>> "%PS1%"
echo Set-WinUserLanguageList zh-CN -Force>> "%PS1%"
echo Set-TimeZone -Id 'China Standard Time'>> "%PS1%"
echo Write-Host '  完成' -ForegroundColor Green>> "%PS1%"
echo.>> "%PS1%"
echo # ── 2. 关闭 Windows Defender ────────────────────────────────>> "%PS1%"
echo Write-Host '【2/10】关闭 Windows Defender...' -ForegroundColor Cyan>> "%PS1%"
echo # 通过组策略注册表彻底禁用（优先级高于Tamper Protection）>> "%PS1%"
echo $defPath = 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender'>> "%PS1%"
echo New-Item -Path $defPath -Force ^| Out-Null>> "%PS1%"
echo Set-ItemProperty -Path $defPath -Name 'DisableAntiSpyware'      -Value 1 -Type DWord>> "%PS1%"
echo Set-ItemProperty -Path $defPath -Name 'DisableAntiVirus'         -Value 1 -Type DWord>> "%PS1%"
echo Set-ItemProperty -Path $defPath -Name 'DisableRealtimeMonitoring' -Value 1 -Type DWord>> "%PS1%"
echo Set-ItemProperty -Path $defPath -Name 'DisableRoutinelyTakingAction' -Value 1 -Type DWord>> "%PS1%"
echo New-Item -Path "$defPath\Real-Time Protection" -Force ^| Out-Null>> "%PS1%"
echo Set-ItemProperty -Path "$defPath\Real-Time Protection" -Name 'DisableRealtimeMonitoring'  -Value 1 -Type DWord>> "%PS1%"
echo Set-ItemProperty -Path "$defPath\Real-Time Protection" -Name 'DisableBehaviorMonitoring'  -Value 1 -Type DWord>> "%PS1%"
echo Set-ItemProperty -Path "$defPath\Real-Time Protection" -Name 'DisableOnAccessProtection'  -Value 1 -Type DWord>> "%PS1%"
echo Set-ItemProperty -Path "$defPath\Real-Time Protection" -Name 'DisableScanOnRealtimeEnable' -Value 1 -Type DWord>> "%PS1%"
echo New-Item -Path "$defPath\Spynet" -Force ^| Out-Null>> "%PS1%"
echo Set-ItemProperty -Path "$defPath\Spynet" -Name 'SpynetReporting'       -Value 0 -Type DWord>> "%PS1%"
echo Set-ItemProperty -Path "$defPath\Spynet" -Name 'SubmitSamplesConsent'  -Value 2 -Type DWord>> "%PS1%"
echo # 关闭Defender相关服务>> "%PS1%"
echo $defSvcs = @('WinDefend','WdNisSvc','Sense','SecurityHealthService','wscsvc','WdNisDrv')>> "%PS1%"
echo foreach ($s in $defSvcs) {>> "%PS1%"
echo     Stop-Service -Name $s -Force>> "%PS1%"
echo     Set-Service  -Name $s -StartupType Disabled>> "%PS1%"
echo     Write-Host "  已禁用Defender服务: $s" -ForegroundColor Gray>> "%PS1%"
echo }>> "%PS1%"
echo # 关闭Defender计划任务>> "%PS1%"
echo Disable-ScheduledTask -TaskPath '\Microsoft\Windows\Windows Defender\' -TaskName 'Windows Defender Cache Maintenance' ^| Out-Null>> "%PS1%"
echo Disable-ScheduledTask -TaskPath '\Microsoft\Windows\Windows Defender\' -TaskName 'Windows Defender Cleanup'           ^| Out-Null>> "%PS1%"
echo Disable-ScheduledTask -TaskPath '\Microsoft\Windows\Windows Defender\' -TaskName 'Windows Defender Scheduled Scan'   ^| Out-Null>> "%PS1%"
echo Disable-ScheduledTask -TaskPath '\Microsoft\Windows\Windows Defender\' -TaskName 'Windows Defender Verification'     ^| Out-Null>> "%PS1%"
echo Write-Host '  Defender已关闭（重启后完全生效）' -ForegroundColor Green>> "%PS1%"
echo.>> "%PS1%"
echo # ── 3. 极限精简服务（仅保留Azure必要项） ───────────────────>> "%PS1%"
echo Write-Host '【3/10】禁用非必要服务（保留Azure/RDP/网络核心）...' -ForegroundColor Cyan>> "%PS1%"
echo # 以下服务在Azure VM上可安全禁用>> "%PS1%"
echo $services = @(>> "%PS1%"
echo     # UI / 主题>> "%PS1%"
echo     'Themes','TabletInputService','UxSms',>> "%PS1%"
echo     # 打印 / 传真>> "%PS1%"
echo     'Spooler','Fax',>> "%PS1%"
echo     # 搜索 / 内存压缩>> "%PS1%"
echo     'WSearch','SysMain',>> "%PS1%"
echo     # 遥测 / 诊断>> "%PS1%"
echo     'DiagTrack','dmwappushservice','WerSvc','PcaSvc','DPS','WdiServiceHost','WdiSystemHost',>> "%PS1%"
echo     # Windows Update（手动维护）>> "%PS1%"
echo     'wuauserv','UsoSvc','DoSvc','WaaSMedicSvc',>> "%PS1%"
echo     # Xbox>> "%PS1%"
echo     'XboxGipSvc','XblAuthManager','XblGameSave','XboxNetApiSvc',>> "%PS1%"
echo     # 地理位置 / 传感器>> "%PS1%"
echo     'lfsvc','SensorDataService','SensrSvc','SensorService',>> "%PS1%"
echo     # 蓝牙 / 红外 / 手机>> "%PS1%"
echo     'bthserv','BthHFSrv','PhoneSvc','RmSvc','icssvc',>> "%PS1%"
echo     # 媒体 / 零售>> "%PS1%"
echo     'WMPNetworkSvc','RetailDemo',>> "%PS1%"
echo     # 地图 / Cortana>> "%PS1%"
echo     'MapsBroker',>> "%PS1%"
echo     # 网络共享 / ICS>> "%PS1%"
echo     'SharedAccess',>> "%PS1%"
echo     # 智能卡>> "%PS1%"
echo     'SCardSvr','SCPolicySvc','CertPropSvc',>> "%PS1%"
echo     # BitLocker / EFS（Azure托管盘不需要）>> "%PS1%"
echo     'BDESVC','EFS',>> "%PS1%"
echo     # 链接追踪 / 备份>> "%PS1%"
echo     'TrkWks','SDRSVC','swprv','wbengine',>> "%PS1%"
echo     # 内部人计划>> "%PS1%"
echo     'wisvc',>> "%PS1%"
echo     # 无线（VM无WiFi）>> "%PS1%"
echo     'WlanSvc','WwanSvc','dot3svc',>> "%PS1%"
echo     # 连接设备平台>> "%PS1%"
echo     'CDPSvc','CDPUserSvc',>> "%PS1%"
echo     # 剪贴板同步 / 安装>> "%PS1%"
echo     'cbdhsvc','InstallService',>> "%PS1%"
echo     # 碎片整理>> "%PS1%"
echo     'defragsvc',>> "%PS1%"
echo     # 辅助功能>> "%PS1%"
echo     'hidserv','stisvc',>> "%PS1%"
echo     # 远程注册表（安全考虑关闭）>> "%PS1%"
echo     'RemoteRegistry',>> "%PS1%"
echo     # 网络连接代理>> "%PS1%"
echo     'NcbService',>> "%PS1%"
echo     # 对等网络>> "%PS1%"
echo     'p2pimsvc','p2psvc','PNRPsvc','PNRPAutoReg',>> "%PS1%"
echo     # IKE/VPN（不用VPN则关闭）>> "%PS1%"
echo     'IKEEXT',>> "%PS1%"
echo     # Shell硬件检测>> "%PS1%"
echo     'ShellHWDetection',>> "%PS1%"
echo     # 预取 / 应用体验>> "%PS1%"
echo     'AeLookupSvc',>> "%PS1%"
echo     # 辅助登录>> "%PS1%"
echo     'seclogon',>> "%PS1%"
echo     # 家庭组>> "%PS1%"
echo     'HomeGroupListener','HomeGroupProvider'>> "%PS1%"
echo )>> "%PS1%"
echo foreach ($svc in $services) {>> "%PS1%"
echo     $s = Get-Service -Name $svc -ErrorAction SilentlyContinue>> "%PS1%"
echo     if ($s) {>> "%PS1%"
echo         Stop-Service -Name $svc -Force>> "%PS1%"
echo         Set-Service  -Name $svc -StartupType Disabled>> "%PS1%"
echo         Write-Host "  已禁用: $svc" -ForegroundColor Gray>> "%PS1%"
echo     }>> "%PS1%"
echo }>> "%PS1%"
echo Write-Host '  服务精简完成' -ForegroundColor Green>> "%PS1%"
echo.>> "%PS1%"
echo # ── 4. 关闭 Windows 功能 ────────────────────────────────────>> "%PS1%"
echo Write-Host '【4/10】关闭不必要的 Windows 功能...' -ForegroundColor Cyan>> "%PS1%"
echo $features = @(>> "%PS1%"
echo     'Internet-Explorer-Optional-amd64',>> "%PS1%"
echo     'MediaPlayback','WindowsMediaPlayer',>> "%PS1%"
echo     'Printing-PrintToPDFServices-Features',>> "%PS1%"
echo     'Printing-XPSServices-Features',>> "%PS1%"
echo     'WorkFolders-Client','FaxServicesClientPackage',>> "%PS1%"
echo     'SMB1Protocol','MicrosoftWindowsPowerShellV2Root'>> "%PS1%"
echo )>> "%PS1%"
echo foreach ($f in $features) {>> "%PS1%"
echo     Disable-WindowsOptionalFeature -Online -FeatureName $f -NoRestart ^| Out-Null>> "%PS1%"
echo     Write-Host "  已关闭: $f" -ForegroundColor Gray>> "%PS1%"
echo }>> "%PS1%"
echo Write-Host '  功能关闭完成' -ForegroundColor Green>> "%PS1%"
echo.>> "%PS1%"
echo # ── 5. 视觉效果最佳性能 ─────────────────────────────────────>> "%PS1%"
echo Write-Host '【5/10】视觉效果调整为最佳性能...' -ForegroundColor Cyan>> "%PS1%"
echo $regVis = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects'>> "%PS1%"
echo if (-not (Test-Path $regVis)) { New-Item -Path $regVis -Force ^| Out-Null }>> "%PS1%"
echo Set-ItemProperty -Path $regVis -Name 'VisualFXSetting' -Value 2>> "%PS1%"
echo Set-ItemProperty -Path 'HKCU:\Control Panel\Desktop' -Name 'MenuShowDelay' -Value '0'>> "%PS1%"
echo Set-ItemProperty -Path 'HKCU:\Control Panel\Desktop' -Name 'DragFullWindows' -Value '0'>> "%PS1%"
echo Set-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced' -Name 'TaskbarAnimations' -Value 0>> "%PS1%"
echo # 关闭透明效果>> "%PS1%"
echo Set-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize' -Name 'EnableTransparency' -Value 0>> "%PS1%"
echo Write-Host '  完成' -ForegroundColor Green>> "%PS1%"
echo.>> "%PS1%"
echo # ── 6. 页面文件固定 2048MB ──────────────────────────────────>> "%PS1%"
echo Write-Host '【6/10】设置虚拟内存页面文件 2048MB...' -ForegroundColor Cyan>> "%PS1%"
echo $cs = Get-WmiObject -Class Win32_ComputerSystem -EnableAllPrivileges>> "%PS1%"
echo $cs.AutomaticManagedPagefile = $false>> "%PS1%"
echo $cs.Put() ^| Out-Null>> "%PS1%"
echo Get-WmiObject -Class Win32_PageFileSetting ^| ForEach-Object { $_.Delete() }>> "%PS1%"
echo Set-WmiInstance -Class Win32_PageFileSetting -Arguments @{Name='C:\pagefile.sys';InitialSize=2048;MaximumSize=2048} ^| Out-Null>> "%PS1%"
echo Write-Host '  页面文件已固定为 2048MB' -ForegroundColor Green>> "%PS1%"
echo.>> "%PS1%"
echo # ── 7. 高性能电源计划 ────────────────────────────────────────>> "%PS1%"
echo Write-Host '【7/10】切换电源计划为高性能...' -ForegroundColor Cyan>> "%PS1%"
echo powercfg /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c>> "%PS1%"
echo powercfg /change standby-timeout-ac 0>> "%PS1%"
echo powercfg /change hibernate-timeout-ac 0>> "%PS1%"
echo Write-Host '  完成' -ForegroundColor Green>> "%PS1%"
echo.>> "%PS1%"
echo # ── 8. 禁用计划任务 ─────────────────────────────────────────>> "%PS1%"
echo Write-Host '【8/10】禁用遥测/诊断/更新计划任务...' -ForegroundColor Cyan>> "%PS1%"
echo $tasks = @(>> "%PS1%"
echo     @{P='\Microsoft\Windows\Application Experience\';    N='Microsoft Compatibility Appraiser'},>> "%PS1%"
echo     @{P='\Microsoft\Windows\Application Experience\';    N='ProgramDataUpdater'},>> "%PS1%"
echo     @{P='\Microsoft\Windows\Application Experience\';    N='StartupAppTask'},>> "%PS1%"
echo     @{P='\Microsoft\Windows\Customer Experience Improvement Program\'; N='Consolidator'},>> "%PS1%"
echo     @{P='\Microsoft\Windows\Customer Experience Improvement Program\'; N='UsbCeip'},>> "%PS1%"
echo     @{P='\Microsoft\Windows\Windows Error Reporting\';   N='QueueReporting'},>> "%PS1%"
echo     @{P='\Microsoft\Windows\UpdateOrchestrator\';        N='Schedule Scan'},>> "%PS1%"
echo     @{P='\Microsoft\Windows\UpdateOrchestrator\';        N='USO_UxBroker'},>> "%PS1%"
echo     @{P='\Microsoft\Windows\UpdateOrchestrator\';        N='Report policies'},>> "%PS1%"
echo     @{P='\Microsoft\Windows\Diagnosis\';                 N='Scheduled'},>> "%PS1%"
echo     @{P='\Microsoft\Windows\DiskDiagnostic\';            N='Microsoft-Windows-DiskDiagnosticDataCollector'},>> "%PS1%"
echo     @{P='\Microsoft\Windows\Maintenance\';               N='WinSAT'},>> "%PS1%"
echo     @{P='\Microsoft\Windows\Maps\';                      N='MapsUpdateTask'},>> "%PS1%"
echo     @{P='\Microsoft\Windows\Maps\';                      N='MapsToastTask'},>> "%PS1%"
echo     @{P='\Microsoft\Windows\Power Efficiency Diagnostics\'; N='AnalyzeSystem'},>> "%PS1%"
echo     @{P='\Microsoft\Windows\Shell\';                     N='FamilySafetyMonitor'},>> "%PS1%"
echo     @{P='\Microsoft\Windows\Shell\';                     N='FamilySafetyRefreshTask'}>> "%PS1%"
echo )>> "%PS1%"
echo foreach ($t in $tasks) {>> "%PS1%"
echo     Disable-ScheduledTask -TaskPath $t.P -TaskName $t.N ^| Out-Null>> "%PS1%"
echo     Write-Host "  已禁用任务: $($t.N)" -ForegroundColor Gray>> "%PS1%"
echo }>> "%PS1%"
echo Write-Host '  计划任务禁用完成' -ForegroundColor Green>> "%PS1%"
echo.>> "%PS1%"
echo # ── 9. 注册表 + 网络优化 ────────────────────────────────────>> "%PS1%"
echo Write-Host '【9/10】注册表 + 网络优化...' -ForegroundColor Cyan>> "%PS1%"
echo # 禁用Cortana>> "%PS1%"
echo New-Item -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search' -Force ^| Out-Null>> "%PS1%"
echo Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search' -Name 'AllowCortana' -Value 0>> "%PS1%"
echo # 遥测归零>> "%PS1%"
echo New-Item -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection' -Force ^| Out-Null>> "%PS1%"
echo Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection' -Name 'AllowTelemetry' -Value 0>> "%PS1%"
echo # 禁用错误报告弹窗>> "%PS1%"
echo New-Item -Path 'HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting' -Force ^| Out-Null>> "%PS1%"
echo Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting' -Name 'Disabled' -Value 1>> "%PS1%"
echo # 加快关机速度>> "%PS1%"
echo Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control' -Name 'WaitToKillServiceTimeout' -Value '2000'>> "%PS1%"
echo # 禁用IPv6（Azure内部走IPv4）>> "%PS1%"
echo Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters' -Name 'DisabledComponents' -Value 0xFF -Type DWord>> "%PS1%"
echo # TCP优化>> "%PS1%"
echo netsh int tcp set global autotuninglevel=normal ^| Out-Null>> "%PS1%"
echo netsh int tcp set global chimney=disabled ^| Out-Null>> "%PS1%"
echo netsh int tcp set global rss=enabled ^| Out-Null>> "%PS1%"
echo netsh int tcp set global timestamps=disabled ^| Out-Null>> "%PS1%"
echo # 禁用LLMNR>> "%PS1%"
echo New-Item -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient' -Force ^| Out-Null>> "%PS1%"
echo Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient' -Name 'EnableMulticast' -Value 0>> "%PS1%"
echo Write-Host '  完成' -ForegroundColor Green>> "%PS1%"
echo.>> "%PS1%"
echo # ── 10. 清理临时文件 ────────────────────────────────────────>> "%PS1%"
echo Write-Host '【10/10】清理临时文件和系统垃圾...' -ForegroundColor Cyan>> "%PS1%"
echo Remove-Item -Path "$env:TEMP\*"         -Recurse -Force>> "%PS1%"
echo Remove-Item -Path 'C:\Windows\Temp\*'   -Recurse -Force>> "%PS1%"
echo Remove-Item -Path 'C:\Windows\Prefetch\*' -Recurse -Force>> "%PS1%"
echo Remove-Item -Path 'C:\Windows\SoftwareDistribution\Download\*' -Recurse -Force>> "%PS1%"
echo # 清理WER报告>> "%PS1%"
echo Remove-Item -Path 'C:\ProgramData\Microsoft\Windows\WER\ReportQueue\*' -Recurse -Force>> "%PS1%"
echo Remove-Item -Path 'C:\ProgramData\Microsoft\Windows\WER\ReportArchive\*' -Recurse -Force>> "%PS1%"
echo Write-Host '  清理完成' -ForegroundColor Green>> "%PS1%"
echo.>> "%PS1%"
echo Write-Host '============================================================' -ForegroundColor Yellow>> "%PS1%"
echo Write-Host '  全部优化完成！请重启系统以完全生效。' -ForegroundColor Yellow>> "%PS1%"
echo Write-Host '  保留的必要服务: RDP(TermService) / WMI / DHCP / DNS' -ForegroundColor Yellow>> "%PS1%"
echo Write-Host '  保留的必要服务: Azure Agent / RPC / EventLog / Netlogon' -ForegroundColor Yellow>> "%PS1%"
echo Write-Host '  Windows Defender 将在重启后完全关闭。' -ForegroundColor Yellow>> "%PS1%"
echo Write-Host '============================================================' -ForegroundColor Yellow>> "%PS1%"

powershell -NoProfile -ExecutionPolicy Bypass -File "%PS1%"
del /f /q "%PS1%" >nul 2>&1

echo.
echo 优化完成！按任意键重启系统（语言/Defender设置需重启后生效）...
echo 如不想立即重启，请直接关闭此窗口。
pause >nul
shutdown /r /t 10 /c "Azure VM优化完成，10秒后重启..."
